export const UserList = [
    {
        id:1,
        name:'Kofi Manu',
        username:'Kofi',
        email:'kofi@email.com',
        depart:'Computer Science',
        interest:'Mobile App Dev',
        phone:'123456',
        friends:[8, 2, 4, 5, 6, 7],
        fav:[2, 4, 6, 7, 8, 5],
        pic:'https://img.freepik.com/premium-vector/anonymous-user-circle-icon-vector-illustration-flat-style-with-long-shadow_520826-1931.jpg?w=2000',
        desc: "I'm a creative, outgoing, and passionate person who loves to explore new things. I'm an avid reader and enjoy learning about different cultures and languages. I'm also a big fan of music, art, and photography. I'm always looking for new ways to express myself and find joy in life."
    },
    {
        id:2,
        name:'Kojo Manu',
        username:'Kojo',
        email:'kojo@email.com',
        depart:'Political Science',
        interest:'Sociology',
        phone:'123456',
        friends:[1, 3, 4, 5, 6, 7],
        fav:[1, 4, 5, 7],
        pic:'https://img.freepik.com/premium-vector/anonymous-user-circle-icon-vector-illustration-flat-style-with-long-shadow_520826-1931.jpg?w=2000',
        desc: "I'm a creative, outgoing, and passionate person who loves to explore new things. I'm an avid reader and enjoy learning about different cultures and languages. I'm also a big fan of music, art, and photography. I'm always looking for new ways to express myself and find joy in life."
    },
    {
        id:3,
        name:'Kwame Manu',
        username:'Kwame',
        email:'kwame@email.com',
        depart:'Economics',
        interest:'E-commerce',
        phone:'123456',
        friends:[1, 2, 7, 5, 6],
        fav:[2, 4, 6, 5],
        pic:'https://img.freepik.com/premium-vector/anonymous-user-circle-icon-vector-illustration-flat-style-with-long-shadow_520826-1931.jpg?w=2000',
        desc: "I'm a creative, outgoing, and passionate person who loves to explore new things. I'm an avid reader and enjoy learning about different cultures and languages. I'm also a big fan of music, art, and photography. I'm always looking for new ways to express myself and find joy in life."
    },
    {
        id:4,
        name:'Kwabena Manu',
        username:'Kwabena',
        email:'kwabena@email.com',
        depart:'Chemistry',
        interest:'Medicine',
        phone:'123456',
        friends:[2, 8, 5, 6, 3],
        fav:[2, 8, 6],
        pic:'https://img.freepik.com/premium-vector/anonymous-user-circle-icon-vector-illustration-flat-style-with-long-shadow_520826-1931.jpg?w=2000',
        desc: "I'm a creative, outgoing, and passionate person who loves to explore new things. I'm an avid reader and enjoy learning about different cultures and languages. I'm also a big fan of music, art, and photography. I'm always looking for new ways to express myself and find joy in life."
    },
    {
        id:5,
        name:'Kwesi Manu',
        username:'Kwesi',
        email:'kwesi@email.com',
        depart:'Agriculture',
        interest:'Animal Husbandry',
        phone:'123456',
        friends:[1, 2, 3, 8, 6, 7],
        fav:[2, 3, 6, 7],
        pic:'https://img.freepik.com/premium-vector/anonymous-user-circle-icon-vector-illustration-flat-style-with-long-shadow_520826-1931.jpg?w=2000',
        desc: "I'm a creative, outgoing, and passionate person who loves to explore new things. I'm an avid reader and enjoy learning about different cultures and languages. I'm also a big fan of music, art, and photography. I'm always looking for new ways to express myself and find joy in life."
    },
    {
        id:6,
        name:'Kweku Manu',
        username:'Kweku',
        email:'kweku@email.com',
        depart:'Physics',
        interest:'Quantum Mechanics',
        phone:'123456',
        friends:[1, 2, 4, 3, 7],
        fav:[2, 4, 6, 1],
        pic:'https://img.freepik.com/premium-vector/anonymous-user-circle-icon-vector-illustration-flat-style-with-long-shadow_520826-1931.jpg?w=2000',
        desc: "I'm a creative, outgoing, and passionate person who loves to explore new things. I'm an avid reader and enjoy learning about different cultures and languages. I'm also a big fan of music, art, and photography. I'm always looking for new ways to express myself and find joy in life."
    },
    {
        id:7,
        name:'Yaw Manu',
        username:'Yaw',
        email:'Yaw@email.com',
        depart:'Music',
        interest:'African Dance',
        phone:'123456',
        friends:[1, 2, 4, 5, 6, 3],
        fav:[2, 4, 6, 5],
        pic:'https://img.freepik.com/premium-vector/anonymous-user-circle-icon-vector-illustration-flat-style-with-long-shadow_520826-1931.jpg?w=2000',
        desc: "I'm a creative, outgoing, and passionate person who loves to explore new things. I'm an avid reader and enjoy learning about different cultures and languages. I'm also a big fan of music, art, and photography. I'm always looking for new ways to express myself and find joy in life."
    },
    {
        id:8,
        name:'Badu Kubi',
        username:'Kubi',
        email:'badu@email.com',
        depart:'Biology',
        interest:'Botany',
        phone:'123456',
        friends:[1, 2, 4, 5, 6, 7],
        fav:[1, 4, 6, 7],
        pic:'https://img.freepik.com/premium-vector/anonymous-user-circle-icon-vector-illustration-flat-style-with-long-shadow_520826-1931.jpg?w=2000',
        desc: "I'm a creative, outgoing, and passionate person who loves to explore new things. I'm an avid reader and enjoy learning about different cultures and languages. I'm also a big fan of music, art, and photography. I'm always looking for new ways to express myself and find joy in life."
    },
]